"""Database creation

Revision ID: 29bf2f8cc1fa
Revises:
Create Date: 2024-04-11 19:51:02.652386

"""

# pylint: disable-all
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29bf2f8cc1fa'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
	# ### commands auto generated by Alembic - please adjust! ###
	op.create_table(
		'authentifications',
		sa.Column('id', sa.Integer(), nullable=False),
		sa.Column('username', sa.String(), nullable=True),
		sa.Column('password', sa.String(), nullable=True),
		sa.Column('data', sa.ARRAY(sa.String), nullable=True),
		sa.PrimaryKeyConstraint('id'),
	)
	op.create_table(
		'users',
		sa.Column('id', sa.Integer(), nullable=False),
		sa.Column('name', sa.String(), nullable=True),
		sa.Column('authentification', sa.Integer(), nullable=True),
		sa.ForeignKeyConstraint(
			['authentification'],
			['authentifications.id'],
		),
		sa.PrimaryKeyConstraint('id'),
	)
	# ### end Alembic commands ###


def downgrade() -> None:
	# ### commands auto generated by Alembic - please adjust! ###
	op.drop_table('users')
	op.drop_table('authentifications')
	# ### end Alembic commands ###
